scrape_configs:
  - job_name: "AuthServiceMetrics"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "Authentication"
