name: Continuous Integration (CI)

on:
  push:
  pull_request:

jobs:
  test:
    name: run tests
    runs-on: ubuntu-22.04
    steps:
      - name: check out the git repository
        uses: actions/checkout@v4
      - name: set up java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: set gradlew executable
        run: chmod +x ./gradlew
      - name: run unit tests
        run: ./gradlew test
